spring.application.name=APIGateway

server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=UserService
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://USERSERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/users/**

spring.cloud.gateway.server.webmvc.routes[1].id=RestaurantService
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://RestaurantService          
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/restaurants/**